export const keys = [
  { id: 0, name: "7", type: "NUMBER" },
  { id: 1, name: "8", type: "NUMBER" },
  { id: 2, name: "9", type: "NUMBER" },
  { id: 3, name: "*", type: "MULTIPLICATION" },
  { id: 4, name: "4", type: "NUMBER" },
  { id: 5, name: "5", type: "NUMBER" },
  { id: 6, name: "6", type: "NUMBER" },
  { id: 7, name: "-", type: "SUBTRACT" },
  { id: 8, name: "1", type: "NUMBER" },
  { id: 9, name: "2", type: "NUMBER" },
  { id: 10, name: "3", type: "NUMBER" },
  { id: 11, name: "+", type: "ADDITION" },
  { id: 12, name: "/", type: "DIVISION" },
  { id: 13, name: "0", type: "NUMBER" },
  { id: 14, name: "C", type: "CLEAR" },
  { id: 15, name: "=", type: "EQUAL" },
];
