export const keys = [
  { id: 0, name: "7", type: "NUMBER", value: 7 },
  { id: 1, name: "8", type: "NUMBER", value: 8 },
  { id: 2, name: "9", type: "NUMBER", value: 9 },
  { id: 3, name: "*", type: "MULTIPLICATION" },
  { id: 4, name: "4", type: "NUMBER", value: 4 },
  { id: 5, name: "5", type: "NUMBER", value: 5 },
  { id: 6, name: "6", type: "NUMBER", value: 6 },
  { id: 7, name: "-", type: "SUBTRACT" },
  { id: 8, name: "1", type: "NUMBER", value: 1 },
  { id: 9, name: "2", type: "NUMBER", value: 2 },
  { id: 10, name: "3", type: "NUMBER", value: 3 },
  { id: 11, name: "+", type: "ADDITION" },
  { id: 12, name: "/", type: "DIVISION" },
  { id: 13, name: "0", type: "NUMBER", value: 0 },
  { id: 14, name: "C", type: "DELETE" },
  { id: 15, name: "=", type: "EQUAL" },
];
